services:
  backend:
    build:
      context: ./backend  #在backend目录下有Dockerfile
    env_file:
      - ./.env  #在根目录下有.env文件，里面包含了后端服务需要的环境变量
    environment:
      SPRING_PROFILES_ACTIVE: prod  #设置Spring Boot的运行环境为生产环境
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend  #在frontend目录下有Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ssl/:/etc/nginx/ssl/:ro
    depends_on:
      - backend
